FROM node:20.9.0-alpine AS build-stage

# Building stage
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
ARG API_URL
ENV VITE_API_URL=$API_URL
RUN npm run build

FROM nginx:stable-alpine AS production-stage

# Launching stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
