version: '3'

name: todo-app-development
services:
  todo-app-db:
    container_name: todo-app-db-dev

  todo-app-api:
    container_name: todo-app-api-dev
    image: todo-app-api-dev
    build:
      dockerfile: dockerfile.development
    environment:
      - NODE_ENV=development
      - CORS_ALLOW_ORIGINS=http://localhost:8001
      - TYPEORM_LOG=true
      - TYPEORM_MODELS_SYNC=true
    volumes:
      - ./api:/app/
      - /app/node_modules

  todo-app-client:
    container_name: todo-app-client-dev
    image: todo-app-client-dev
    build:
      dockerfile: dockerfile.development
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080/api
      - VITE_PORT=8001
    volumes:
      - ./client:/app/
      - /app/node_modules
