version: '3'

name: todo-app-production
services:
  todo-app-api:
    container_name: todo-app-api
    build:
      dockerfile: dockerfile.production
    environment:
      - NODE_ENV=production
      - CORS_ALLOW_ORIGINS=http://localhost:8081

  todo-app-client:
    container_name: todo-app-client
    build:
      dockerfile: dockerfile.production
      args:
        API_URL: http://localhost:8080/api
    ports:
      - 8081:80
    environment:
      - NODE_ENV=production
