FROM node:20.9.0-alpine

# Building stage
WORKDIR /app/src
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
RUN cp -r ./build/* /app/

# Launching stage
WORKDIR /app
RUN rm -rf ./src
COPY package*.json ./
RUN npm install --omit=dev
CMD node app.js
