FROM node:20.9.0-alpine

# Building stage
WORKDIR /app/pre-build
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
RUN cp -r ./dist/src/* /app/

# Launching stage
WORKDIR /app
RUN rm -rf ./pre-build
COPY package*.json ./
RUN npm install --omit=dev
CMD ["npm", "run", "start"]
